### ISSUE TITLE
unable to edit options

### ISSUE THREAD

**Issue by kigod0192** [FelixRilling/di-ngy#3]
How do I disable the help command?

**Comment by FelixRilling** [comment]
you can set `enableDefaultCommands` to false to disable all built-in commands, if you want the other default commands to work, you can register them manually again.

**Comment by FelixRilling** [comment]
Hmm, weird. I'll look into it.

**Comment by FelixRilling** [comment]
Hey, this should be fixed with v7.1.2, could you test it with that version?

**Comment by kigod0192** [comment]
It works perfectly now, thank you!
